# removed the -c option because we need to link this
HelloWorld:
	gcc -shared -Wall -Werror -IC:\sdkman\candidates\java\current\include -IC:\sdkman\candidates\java\current\include\win32 -o HelloWorld.dll -fPIC HelloWorld.c
clean:
	rm -f *.o 
